# ─────────────────────────────────────────────
# Stage 1: Install dependencies
# ─────────────────────────────────────────────
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

# ─────────────────────────────────────────────
# Stage 2: Build the Next.js application
# ─────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time env vars (non-secret, baked into JS bundle)
# These must be set at build time — Next.js bakes NEXT_PUBLIC_ vars into the client bundle.
# Pass them via: docker build --build-arg NEXT_PUBLIC_SUPABASE_URL=... etc.
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_MAPLIBRE_STYLE_URL
ARG NEXT_PUBLIC_MAP_PROVIDER

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_MAPLIBRE_STYLE_URL=$NEXT_PUBLIC_MAPLIBRE_STYLE_URL
ENV NEXT_PUBLIC_MAP_PROVIDER=$NEXT_PUBLIC_MAP_PROVIDER
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Clean all caches before building to ensure fresh build
RUN rm -rf .next .turbo node_modules/.cache node_modules/.vite turbopack-cache .swc && npm run build

# ─────────────────────────────────────────────
# Stage 3: Production runner (minimal image)
# ─────────────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy standalone output (generated by output: 'standalone' in next.config.ts)
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static /app/.next/static
RUN chown -R nextjs:nodejs /app/.next

# Copy public assets if they exist (this project currently has none,
# but the COPY is safe to keep for future additions)
# COPY --from=builder /app/public ./public

USER nextjs

EXPOSE 3000

# server.js is generated by Next.js standalone build
CMD ["node", "server.js"]
